### ISSUE TITLE
experienceevent web field

### ISSUE THREAD

**Issue by cmathis** [adobe/xdm#142]
@trieloff and @kstreeter 

In the experienceevent schema today we have this xdm:web field that is referencing a channel/web schema that does not have the information that this was originally meant to store. This xdm:web field is intended to store web related information about the page meta-data (name, isErrorPage, isHomepage, referrer, etc.) and link meta-data (linkName, URL, etc.). The channel/webpage and context/weblink are still around, but they are not being used. The original context/web that we pushed over included those, but somewhere this was removed and the reference was change to channel/web which seems like a different purpose. 

Wondering what we should do in this case. Do we add the webpage and weblink references to the channel/web or bring back the context/web as before with those included. 

cc @jwen-adobe

**Comment by jwen-adobe** [comment]
A PR is created for creating another web schema under context folder while keep the channels/web as is.  Another option is replace the web with webpage and weblink in the experienceevent schema.
PR: https://github.com/adobe/xdm/pull/143

**Comment by trieloff** [comment]
Notes from conversation with @kstreeter 
- [ ] channel independent representation will make it harder to produce, but easier to consume (we prioritize consumability)
- [ ] we need to look at page name as a way to identify channel locations in places where URLs are absent (mobile) or weak (legacy web apps)
- [ ] we need good documentation on best practices for creating experience events, so that crucial properties aren't forgotten
- [ ] we need more (and channel-specific) examples for experience events

**Comment by trieloff** [comment]
I will try to create an alternative PR for this.

**Comment by cmathis** [comment]
@trieloff - Are you saying an alternative PR to the existing #143?  

If this the case please let me know what we can do to speed this along. Teams are expecting this expereinceevent schema to be stable right after Summit. We have another small change we may need to make, but I'm waiting to see what we end up with here before I do anything else. 

cc @kstreeter @cdegroot-adobe

**Comment by trieloff** [comment]
Please give feedback on #186
