### ISSUE TITLE
Method of defining tags or keyword

### ISSUE THREAD

**Issue by ieb** [adobe/xdm#40]
## What are the schemas that are affected by the issue

https://ns.adobe.com/xdm/assets/asset
but might be its own schema or impact other schema.

## What are examples of products that are impacted by the issue

AEM and other products that store content that needs to be tagged.

While the assets schema has xmp:keywords and xmp:machineKeywords which might be used to tag an asset with a keyword, there is no XDM way of describing a keyword or organising a keyword into an ontology of tags, even if that ontology is flat.

Many products that store content organise that content using tags and organise those tags into an ontology. Some examples:

Example 1.
In a DAM, Photographs may be tagged with "cars" which would be organised as a narrower term for "vehicles" and cards would contain narrower terms of "performance", "family".

Example 2.
In a Drugs dictionary, Documents containing medical advice for prescription drugs may be tagged with the family of drug and the families of drugs that cause adverse interactions, hence a patient taking Asprin, classified as a salicylate and a nonsteroidal anti-inflammatory drug would alerted that it has a serious interaction with Ketorolac, by virtue of Aspirin being a NSAIDs. Each tag would be defined in a managed ontology. 

Example 3.
In an audience targeting platform, the segments into which browsers are placed would be related to one another.

The structure of defined tags or keywords needs to support both hierarchical (DAG) and non DAG type graphs, although most uses are probably for hierarchical relationships rather than multi faceted relationships between the keyword or tag definitions.

The ask is for
a) A schema to define the tags and keywords
b) a mechanism to define the relationships between those definitions.

**Comment by lrosenthol** [comment]
Use of tags from an ontology (or not) and how tags are organized (DAG or not) is out of scope.  IMO, that's an application level consideration.  XDM and ACP are only concerned with providing the CRUD operations (and associated storage/APIs) for the data - it's up to each application to consider how to use them.

**Comment by trieloff** [comment]
I’d say that managed ontologies are definitely a concern that spans more than just one product and would be open to including it in XDM, even more so if we can rely on an existing standard that we just model in JSON.

**Comment by lrosenthol** [comment]
I would object to that @trieloff.   If a group of application wish to define such ontologies of tags, that's fine to.  But should have no bearing on the model for simply storing and managing the values.

**Comment by ieb** [comment]
One of the reasons for raising this is because apparently unconnected applications need to interoperate and it is wrong to assume that all applications fall into neat groups where every application knows everything about its peers and so can privately agree on a internal schema. 

AFAIK, there are plenty of standards in XML/RFD . (eg OWL etc) for this area, but none are expressed in json or json-schema. If there is a standard then getting all applications that need to deal with ontologies to use it resolves this issue. If not, something needs to be done.

AEM could easily create its own standard and leave it to other applications to follow, but I do not believe is the behaviour of a good citizen in an XDM enabled world.

**Comment by trieloff** [comment]
Hi @lrosenthol, I agree that we cannot change the semantics of `xmp:keywords` or `xmp:machineKeywords` after the fact.

However, the ability to manage, exchange, and collaborate on taxonomies and managed vocabularies is something that is useful for the discipline of asset management as a whole and already implemented in our products (in currently incompatible ways)

* [Nested keywords in Bridge](https://helpx.adobe.com/bridge/kb/nested-hierarchal-keywording-bridge.html)
* [Tags in AEM](https://helpx.adobe.com/experience-manager/6-3/sites/authoring/using/tags.html)
* [Keywords in Adobe Stock](https://helpx.adobe.com/stock/how-to/keyword-title-best-practices.html)

So, let's model the tags or keywords themselves as suggested by @ieb, maybe using something like [JSKOS](https://gbv.github.io/jskos/jskos.html#concept-schemes), and then find a way of non-destructively referring to them from content or asset metadata.

**Comment by ieb** [comment]
+1, the core of JSKOS is compatible with https://www.w3.org/TR/skos-reference/ and the examples at the end of the JSKOS spec cover the use cases mentioned so far.

**Comment by gklebus** [comment]
I would be in favor of having a common definition of taxonomies / managed vocabularies in the platform, at least to a certain extent. The current situation that we have is _de facto_ leaving that to applications, and that naturally leads to each application to define and use its own -- so if we continue that way, we're guaranteed to have this inconsistencies even within Adobe own solutions / applications. 

To add to your list @trieloff, we also have (just from the top of my head):
- keywords in CC desktop applications (PS, AI, ID, etc) in the File Info dialog - I believe these are compatible with Bridge's keywords
- Smart Tags in AEM

There is of course a fine line of what should be defined on the platform level, and what specific applications could extend.

**Comment by lrosenthol** [comment]
@trieloff you wrote:
>taxonomies and managed vocabularies is something that is useful for the discipline of asset management

And that's my problem here.  You folks are so used to building and running an _asset management system_ (aka AEM and all its children) that you miss the larger picture of ACP & XDM.  Both are used for numerous applications that have *nothing* to do with asset management.  Yes, we have assets, but they aren't being managed (in the traditional/formal sense).   So bringing in anything formal, such as forced ontologies doesn't fit.

**Comment by trieloff** [comment]
@lrosenthol I don't want to force the use of managed ontologies on anyone, but I want to enable the use of them. 

So yes, some applications built on top of XDM will be asset management systems, with asset management requirements.

Some applications will be around content management, and will also be able to benefit from managed taxonomies.

Most applications, however won't and won't care that taxonomies are included in XDM, as long as they don't have to use them. I wouldn't accept anything that makes taxonomies required, but I can't see why I should reject something that makes them optional, when they are useful.

After all, we have a `geo` object defined in XDM, and most applications couldn't care less about the geo-location of anything. Even some that do, simply treat geolocations as lat/lon pairs, and that's fine, too.

To follow that analogy: if the PR for `geo` would have changed the semantics of `exif:gpsLatitude` or `exif:gpsLongitude`, it should have been rejected.

**Comment by trieloff** [comment]
@gklebus wrote: 
> keywords in CC desktop applications (PS, AI, ID, etc) in the File Info dialog - I believe these are compatible with Bridge's keywords

These use `xmp:keywords`.

> Smart Tags in AEM

This should be `xmp:machineKeywords`

----

As @lrosenthol pointed out, we cannot simply change the meaning of either `xmp:keywords` or `xmp:machineKeywords` to point to a list of terms in a managed taxonomy. This means if we introduce a way of linking to a managed taxonomy, it needs to manifest itself inside the asset with a different property.

**Comment by lrosenthol** [comment]
As long as it's not mandatory - I fully support having a way to link to one and/or use it appropriately.

**Comment by jameslockman** [comment]
Keywords don't live in xmp:keywords. They live in the Dublin Core Subject `dc:subject` AND in the Lightroom Hierarchical Subject `lr:hierarchicalSubject` nodes. Bridge and Lightroom understand that these two nodes define the lowest level keyword AND the hierarchy in which the keyword resides. AEM does not understand this multi-node metadata behavior. 

AEM Tags, however, live in `cq:tags`. In order to support AEM Tags, which are stored in `cq:tags` and use a flattened hierarchy `namespace:topLevelProperty/nextLevelProperty/.../lastLevelProperty`, we had to build a new interface in Bridge that allowed us to define the URI and property we wanted to display, and also how to decode their hierarchy. We also had to ensure that when a user changed a property that it got written back to the asset in the same format, so as not to break how AEM managed its tags. 

But, what is a keyword, anyway? A seemingly simple idea like Keywords has been made complex by Adobe (and others) leveraging existing structures for their own purpose. Why did we use Dublin Core Subject for Keywords? I don't know, but it is something we're stuck with now. Customers co-opt existing metadata fields from multiple schemas for their own purposes. Many customers embed JSON into the description, for instance, to embed rich process metadata in the asset without developing a new schema. Since description is just a text field, it's suited for this new application. @trieloff to say that we can't change the meaning of a field is not realistic, as customers do it all the time. If the field is proprietary to Adobe and Adobe's asset management and marketing automation solutions, then be sure to make that very clear to all end users who might be tempted to repurpose it for something else that fits THEIR workflow or backend business process.

I agree with @lrosenthol that the specification should define how to store and retrieve data. The consuming application will need to make sense of the data and express it in a meaningful way to the end user. My team is working on this challenge now, for a general purpose metadata panel for CC apps. We will allow the user to specify ANY property (from URI:property) and how it should be rendered (is it a menu, or a text field, or a date picker, or are there specific constrained values etc). In FileInfo, you can specify a schema and a view separately, to tell FileInfo what to expect and also how to render it.

If the intent is to also define and constrain the data structures that the new model supports, as @trieloff seems to suggest, then I'm OK with that, so long as we are very clear with all consumers that breaking the data structure will have potentially implications. Bridge, Lightroom and FileInfo already support read-only fields, and there's a lot of "hidden" metadata they won't show without UI customization.

I'm curious: how do you expect to support a hierarchical data structure? Like AEM does (with one string and separators for the namespace and hierarchical data) or with two or more related fields (like Bridge and Lightroom do with dc:subject and lr:hierarchicalSubject)? JSON is great, because we can define complex data structures within the field and include a method for defining relationships between properties. Think of how Photoshop currently tracks its the sources for a document in:
```
        <photoshop:DocumentAncestors>
            <rdf:Bag>
               <rdf:li>xmp.did:24dac245-94e2-4322-8ab9-8f0921491bc3</rdf:li>
            </rdf:Bag>
         </photoshop:DocumentAncestors>

```
or Apple tracks faces in:
```
            <mwg-rs:RegionList>
               <rdf:Seq>
                  <rdf:li rdf:parseType="Resource">
                     <mwg-rs:Type>Face</mwg-rs:Type>
                     <mwg-rs:Area rdf:parseType="Resource">
                        <stArea:y>0.31899999999999995</stArea:y>
                        <stArea:w>0.05099999999999999</stArea:w>
                        <stArea:x>0.34150000000000003</stArea:x>
                        <stArea:h>0.068000000000000005</stArea:h>
                        <stArea:unit>normalized</stArea:unit>
                     </mwg-rs:Area>
                     <mwg-rs:Extensions rdf:parseType="Resource">
                        <apple-fi:AngleInfoYaw>0</apple-fi:AngleInfoYaw>
                        <apple-fi:AngleInfoRoll>0</apple-fi:AngleInfoRoll>
                        <apple-fi:ConfidenceLevel>1000</apple-fi:ConfidenceLevel>
                        <apple-fi:Timestamp>2147483647</apple-fi:Timestamp>
                        <apple-fi:FaceID>2</apple-fi:FaceID>
                     </mwg-rs:Extensions>
                  </rdf:li>
               </rdf:Seq>
            </mwg-rs:RegionList>

```
We could probably make this simpler for the kinds of marketing data you want to store with this new mechanism. Are you planning to extend XMP or provide a completely new model for on-asset metadata storage, or is this intended only for a DAM or other asset management system?

**Comment by lrosenthol** [comment]
As always, great stuff @jameslockman.  
There are no plans to extend XMP here - though we are working on a standardized transform from XMP->JSON-LD (and vice-versa) that will certainly find a place in our implementations (and potentially our APIs).  
The issue here is more about the system storage and not the in-asset storage - and how we do so...

**Comment by trieloff** [comment]
> Keywords don't live in `xmp:keywords`. They live in the Dublin Core Subject `dc:subject` AND in the Lightroom Hierarchical Subject `lr:hierarchicalSubject` nodes. Bridge and Lightroom understand that these two nodes define the lowest level keyword AND the hierarchy in which the keyword resides. AEM does not understand this multi-node metadata behavior.

I forgot about `dc:subject` and we do not have `lr: hierarchicalSubject` defined. @lrosenthol should we?

**Comment by lrosenthol** [comment]
dc:subject - yes, because it's used all over our apps.  lr:hierachicalSubject is a problem, IMO, as it's an app-specific approach to a solution that doesn't fit (IMO) our longer term plans.  Personally, I'd like to see it go away...

**Comment by lrosenthol** [comment]
This appears to be also be important in XC for things like offer management (#245 )

**Comment by trieloff** [comment]
I'll have to see if this is an unmanaged vocabulary (which we can model well with `keywords`/`machineKeywords`) or an ontology like this issue describes.

**Comment by alexkli** [comment]
@trieloff I believe this issue can be closed. Content related fields are no longer in XDM.
